### ISSUE TITLE
Failed to open model filefix: 

### ISSUE THREAD

**Issue by Zeehshan** [piekarskipiotr/flutter-nude-detector#7] opened 2023-07-06 18:56 UTC
java.io.FileNotFoundException: assets/ml_models/nude.tflite

**Comment by piekarskipiotr** [comment] 2023-07-06 19:02
Try to run `flutter pub get` if this won't help, please share your folders structure that shows where you put the nude.tflite file & pubspec.yaml file code

**Comment by Zeehshan** [comment] 2023-07-06 19:18
<img width="255" alt="Screenshot 2023-07-07 at 12 18 28 AM" src="https://github.com/piekarskipiotr/flutter-nude-detector/assets/25202051/bc2ca1cd-042c-4763-98ba-46
<img width="301" alt="Screenshot 2023-07-07 at 12 18 46 AM" src="https://github.com/piekarskipiotr/flutter-nude-detector/assets/25202051/8d80debc-f95a-4cf3-89c7-109892cac0dd">
115b7781d0">

**Comment by Zeehshan** [comment] 2023-07-06 19:19
<img width="249" alt="Screenshot 2023-07-07 at 12 19 34 AM" src="https://github.com/piekarskipiotr/flutter-nude-detector/assets/25202051/eb872e8b-6292-4a27-9fc3-2ae014aca8fd">

**Comment by Zeehshan** [comment] 2023-07-06 19:29
I have also checked example app, same thing happing

**Comment by piekarskipiotr** [comment] 2023-07-07 11:25
I can't reproduce the error with the example app
EDIT: ok I got it 😮‍💨 working on it

**Comment by piekarskipiotr** [comment] 2023-07-08 13:53
The issue has been resolved in commit 6272777aba9ae1fe69779e19cbc38304154d8743 😮‍💨 To ensure that you have the latest fix, please update your package to version 0.0.4 ✌🏻

**Closed as completed by piekarskipiotr** 2023-07-08 13:53 UTC
Labels: bug

**Comment by Zeehshan** [comment] 2023-07-08 13:59
Yes i did the same yesterday and get resolved, thanks for the package update.
